import React from "react";
import { Metadata } from "next";
import { SubPageLayout } from "@/components/layout";
import { HeroSection, RelatedLinksModule } from "@/components/blocks";

export const metadata: Metadata = {
  title: "Privacy Policy | CardsFlow",
  description: "Privacy Policy for CardsFlow.",
};

export default function privacyPage() {
  return (
    <SubPageLayout>
      <HeroSection
        title="Privacy Policy"
        supportCopy="Cardsflow policies and documentation for users and partners."
      />
      <div className="max-w-4xl mx-auto px-5 sm:px-12 lg:px-20 py-16 prose prose-slate prose-p:text-slate-600 prose-headings:text-slate-900 prose-headings:font-bold prose-headings:tracking-tight prose-li:text-slate-600 prose-a:text-teal-600">
        <p className="text-sm text-slate-500 italic mb-8">Last Updated: April 29, 2026  |  Version: 2.0</p>
        <p>Your money, your life â€” that principle shapes how we handle your personal data.</p>
        <p>Questions? privacy@cardsflow.net</p>
        <p>We collect as little as possible. We store only what we need. We never sell your data. Ever.</p>
        <h3>1.  DATA CONTROLLER</h3>
        <p>The organisation responsible for your personal data is:</p>
        <p>Name</p>
        <p>CardsFlow</p>
        <p>Address</p>
        <p>[Full Registered Address]</p>
        <p>Email</p>
        <p>privacy@cardsflow.net</p>
        <h3>2.  DATA PROTECTION OFFICER</h3>
        <p>Contact our DPO directly for any data protection concern relating to your personal data.</p>
        <p>DPO Email</p>
        <p>dpo@cardsflow.net</p>
        <h3>3.  DATA WE COLLECT</h3>
        <p>We apply data minimisation throughout. The table below lists every category of personal data we collect, where it comes from, and why we need it.</p>
        <p>Category</p>
        <p>What It Includes</p>
        <p>Source</p>
        <p>Identity data</p>
        <p>Name, date of birth, nationality</p>
        <p>You provide at signup</p>
        <p>Contact data</p>
        <p>Email, postal address, phone number</p>
        <p>You provide at signup</p>
        <p>Eligibility token</p>
        <p>A ZK cryptographic proof of eligibility. No documents. No biometrics. No raw data.</p>
        <p>Generated by verification partner</p>
        <p>Financial data</p>
        <p>E-Money balance, transaction history, tokenised card references. We never store raw card numbers.</p>
        <p>Generated through use of Service</p>
        <p>Technical data</p>
        <p>IP address, browser type, device type, operating system, session data</p>
        <p>Automatically collected</p>
        <p>Usage data</p>
        <p>Pages visited, session duration. Aggregate counts only. Not linked to you.</p>
        <p>Simple Analytics (cookieless)</p>
        <p>Communications data</p>
        <p>Emails and support messages sent to us</p>
        <p>You send to us</p>
        <h3>4.  PURPOSES AND LEGAL BASES</h3>
        <p>We process your data only for the purposes listed below. We have a legal basis for every activity.</p>
        <p>Purpose</p>
        <p>Legal Basis</p>
        <p>Create and manage your Account</p>
        <p>Contract (Art. 6(1)(b) UK GDPR)</p>
        <p>Verify eligibility via ZK proofs</p>
        <p>Legal obligation (Art. 6(1)(c) UK GDPR)</p>
        <p>Issue and manage Cards</p>
        <p>Contract (Art. 6(1)(b) UK GDPR)</p>
        <p>Process Transactions via NowPayments</p>
        <p>Contract (Art. 6(1)(b) UK GDPR)</p>
        <p>Detect and prevent fraud</p>
        <p>Legitimate interests (Art. 6(1)(f) UK GDPR)</p>
        <p>AML compliance via NowPayments</p>
        <p>Legal obligation (Art. 6(1)(c) UK GDPR)</p>
        <p>Platform analytics â€” Simple Analytics (aggregate, anonymous only)</p>
        <p>Legitimate interests (Art. 6(1)(f)). No personal data processed.</p>
        <p>Respond to support queries</p>
        <p>Contract and legitimate interests</p>
        <p>Send transactional emails</p>
        <p>Contract (Art. 6(1)(b) UK GDPR)</p>
        <p>Send marketing emails</p>
        <p>Consent (Art. 6(1)(a)) â€” withdraw anytime</p>
        <p>We will never sell your personal data, share it for third-party advertising, or use it for purposes beyond those listed above without telling you first.</p>
        <h3>5.  THIRD-PARTY PROCESSORS</h3>
        <p>We share data only where necessary, with processors bound by data processing agreements under UK GDPR.</p>
        <p>Processor</p>
        <p>Purpose</p>
        <p>Location</p>
        <p>NowPayments</p>
        <p>nowpayments.io</p>
        <p>Payment processing and transaction AML monitoring. Their AML programme applies.</p>
        <p>EU / Global</p>
        <p>(SCCs in place)</p>
        <p>Amazon Web Services (AWS)</p>
        <p>aws.amazon.com</p>
        <p>Platform hosting and encrypted data storage</p>
        <p>EU region</p>
        <p>SendGrid</p>
        <p>sendgrid.com</p>
        <p>Transactional email delivery</p>
        <p>USA (SCCs in place)</p>
        <p>Simple Analytics</p>
        <p>simpleanalytics.com</p>
        <p>Privacy-first website analytics. No cookies. No personal data. Aggregate counts only.</p>
        <p>EU (Netherlands)</p>
        <p>GDPR compliant by design</p>
        <p>Privacy-Preserving Verification Partner</p>
        <p>ZK eligibility proofing. Returns only a cryptographic proof of eligibility. No raw identity data is shared with CardsFlow.</p>
        <p>We do not use Google Analytics, Meta Pixel, Hotjar, Intercom, or any advertising network. No other third-party tools are used on cardsflow.net.</p>
        <h3>6.  INTERNATIONAL DATA TRANSFERS</h3>
        <p>Where personal data is transferred outside the UK or EEA, we ensure appropriate safeguards are in place including Standard Contractual Clauses (SCCs) approved by the UK ICO or European Commission, and adequacy decisions where applicable.</p>
        <p>NowPayments processes transactions globally. Their international transfer safeguards are documented at nowpayments.io/privacy-policy. For details on safeguards for any specific transfer, email privacy@cardsflow.net.</p>
        <h3>7.  RETENTION PERIODS</h3>
        <p>We hold your data only as long as legally required or operationally necessary.</p>
        <p>Data Category</p>
        <p>Retention Period</p>
        <p>Account and identity data</p>
        <p>Duration of account + 6 years</p>
        <p>Eligibility tokens (ZK proofs)</p>
        <p>Duration of account + 5 years (ML Regulations 2017, Reg. 40)</p>
        <p>Transaction records</p>
        <p>Duration of account + 6 years (HMRC / Companies Act)</p>
        <p>Support communications</p>
        <p>3 years from last interaction</p>
        <p>Technical and log data</p>
        <p>13 months rolling</p>
        <p>Marketing preferences</p>
        <p>Until consent withdrawn or account closed</p>
        <p>Analytics data</p>
        <p>Not applicable â€” Simple Analytics stores no personal data</p>
        <p>After each retention period, data is securely deleted or irreversibly anonymised. We do not hold data longer than required.</p>
        <h3>8.  YOUR RIGHTS</h3>
        <p>Right</p>
        <p>What It Means</p>
        <p>Access</p>
        <p>Request a copy of all personal data we hold about you.</p>
        <p>Rectification</p>
        <p>Request correction of inaccurate or incomplete data. Update basic details in your Dashboard.</p>
        <p>Erasure</p>
        <p>Request deletion of your data where it is no longer necessary or where you withdraw consent. Note: we may retain legally required data (e.g., transaction records under AML law).</p>
        <p>Restriction</p>
        <p>Request that we pause processing of your data in certain circumstances.</p>
        <p>Portability</p>
        <p>Receive your data in a structured, machine-readable format (CSV or JSON) to transfer to another provider.</p>
        <p>Objection</p>
        <p>Object to processing based on legitimate interests. Absolute right to object to direct marketing at any time.</p>
        <p>Withdraw Consent</p>
        <p>Withdraw consent for marketing at any time via unsubscribe link or privacy@cardsflow.net.</p>
        <p>Human Review</p>
        <p>Request human review of any automated decision with significant legal effect on you.</p>
        <h3>9.  HOW TO EXERCISE YOUR RIGHTS</h3>
        <p>Email</p>
        <p>privacy@cardsflow.net</p>
        <p>Response time</p>
        <p>Within 30 calendar days of receipt</p>
        <p>Fee</p>
        <p>None in normal circumstances. We may ask you to confirm your identity before processing.</p>
        <h3>10.  RIGHT TO LODGE A COMPLAINT</h3>
        <p>If you believe we have handled your personal data unlawfully, you have the right to contact the UK Information Commissioner&apos;s Office (ICO). We would appreciate the opportunity to address your concern first â€” please email privacy@cardsflow.net before contacting the ICO.</p>
        <p>ICO Website</p>
        <p>ico.org.uk</p>
        <p>ICO Helpline</p>
        <p>0303 123 1113</p>
        <p>ICO Post</p>
        <p>Wycliffe House, Water Lane, Wilmslow, Cheshire, SK9 5AF</p>
        <h3>11.  CHANGES TO THIS POLICY</h3>
        <p>We will update this Policy when our data practices change. Material changes will be notified by email at least 30 days before taking effect. The &quot;Last Updated&quot; date at the top of this page reflects the most recent revision.</p>

      </div>
      <RelatedLinksModule
        links={[
          { title: "Terms of Service", href: "/legal/terms" },
          { title: "Privacy Policy", href: "/legal/privacy" },
          { title: "Cookie Policy", href: "/legal/cookies" },
          { title: "AML Policy", href: "/legal/aml-policy" }
        ].filter(l => l.href !== "/legal/privacy")}
      />
    </SubPageLayout>
  );
}
